export const MOCK_COURSES = [
  {
    _id: 'course_math_01',
    title: 'Basic Mathematics',
    description: 'Master numbers, arithmetic and everyday maths.',
    subject: 'math',
    level: 'beginner',
    language: 'en',
    totalXp: 350,
    estimatedHours: 3,
    downloadSizeKb: 120,
    tags: ['numbers', 'arithmetic'],
    emoji: '🔢',
    color: '#2C5EAD',
  },
  {
    _id: 'course_sci_01',
    title: 'Our Natural World',
    description: 'Explore plants, animals and the environment.',
    subject: 'science',
    level: 'beginner',
    language: 'en',
    totalXp: 280,
    estimatedHours: 2,
    downloadSizeKb: 95,
    tags: ['nature', 'biology'],
    emoji: '🌿',
    color: '#1591DC',
  },
  {
    _id: 'course_lit_01',
    title: 'Reading & Writing',
    description: 'Build strong literacy skills from the ground up.',
    subject: 'literacy',
    level: 'beginner',
    language: 'en',
    totalXp: 400,
    estimatedHours: 4,
    downloadSizeKb: 80,
    tags: ['reading', 'writing'],
    emoji: '📖',
    color: '#4BB8FA',
  },
  {
    _id: 'course_health_01',
    title: 'Community Health',
    description: 'Essential health knowledge for your community.',
    subject: 'health',
    level: 'beginner',
    language: 'en',
    totalXp: 320,
    estimatedHours: 2.5,
    downloadSizeKb: 110,
    tags: ['health', 'hygiene'],
    emoji: '❤️',
    color: '#2C5EAD',
  },
  {
    _id: 'course_agri_01',
    title: 'Smart Farming',
    description: 'Modern and traditional farming techniques.',
    subject: 'agriculture',
    level: 'beginner',
    language: 'en',
    totalXp: 360,
    estimatedHours: 3,
    downloadSizeKb: 130,
    tags: ['farming', 'crops'],
    emoji: '🌾',
    color: '#1591DC',
  },
  {
    _id: 'course_tech_01',
    title: 'Introduction to Technology',
    description: 'Learn how technology works and how to use it.',
    subject: 'technology',
    level: 'beginner',
    language: 'en',
    totalXp: 300,
    estimatedHours: 2,
    downloadSizeKb: 90,
    tags: ['tech', 'digital'],
    emoji: '💡',
    color: '#4BB8FA',
  },
];

export const MOCK_COURSE_BUNDLE = (courseId) => ({
  version: 1,
  bundledAt: new Date().toISOString(),
  course: {
    _id: courseId,
    title: 'Basic Mathematics',
    description: 'Master numbers, arithmetic and everyday maths.',
    subject: 'math',
    level: 'beginner',
    totalXp: 350,
    estimatedHours: 3,
    lessons: [
      {
        _id: `${courseId}_l1`,
        title: 'Counting Numbers',
        order: 1,
        type: 'text',
        content: '# Counting Numbers\n\nNumbers are the foundation of mathematics. We use numbers every day — to count objects, measure things, and describe quantities.\n\n## The Number Line\n\nImagine a straight line with numbers placed at equal intervals: 0, 1, 2, 3, 4, 5...\n\nEach number is exactly one step from the next.\n\n## Let\'s Practice\n\nCount the items you can see around you right now. How many fingers do you have? How many windows are in the room?',
        durationMinutes: 5,
        xpReward: 20,
        quiz: [],
      },
      {
        _id: `${courseId}_l2`,
        title: 'Addition Basics',
        order: 2,
        type: 'quiz',
        content: '# Addition\n\nAddition means combining two or more numbers together.\n\n**2 + 3 = 5**\n\nThink of it as: if you have 2 mangoes and someone gives you 3 more, you now have 5 mangoes.',
        durationMinutes: 8,
        xpReward: 40,
        quiz: [
          { question: 'What is 4 + 3?', options: ['5', '6', '7', '8'], correctIndex: 2, explanation: '4 + 3 = 7. Count 4 then add 3 more: 5, 6, 7.' },
          { question: 'What is 10 + 5?', options: ['14', '15', '16', '20'], correctIndex: 1, explanation: '10 + 5 = 15.' },
          { question: 'Mary has 6 eggs. She finds 4 more. How many eggs?', options: ['8', '9', '10', '11'], correctIndex: 2, explanation: '6 + 4 = 10 eggs.' },
        ],
      },
      {
        _id: `${courseId}_l3`,
        title: 'Subtraction',
        order: 3,
        type: 'quiz',
        content: '# Subtraction\n\nSubtraction means taking away from a number.\n\n**8 - 3 = 5**\n\nIf you had 8 naira and spent 3 naira, you now have 5 naira left.',
        durationMinutes: 8,
        xpReward: 40,
        quiz: [
          { question: 'What is 9 - 4?', options: ['3', '4', '5', '6'], correctIndex: 2, explanation: '9 - 4 = 5.' },
          { question: 'What is 15 - 7?', options: ['7', '8', '9', '6'], correctIndex: 1, explanation: '15 - 7 = 8.' },
        ],
      },
      {
        _id: `${courseId}_l4`,
        title: 'Multiplication',
        order: 4,
        type: 'text',
        content: '# Multiplication\n\nMultiplication is repeated addition.\n\n**3 × 4 = 12** means adding 3 four times: 3 + 3 + 3 + 3 = 12\n\n## Times Tables\n\nLearning your times tables makes maths faster. Start with 2s and 5s — they have clear patterns.',
        durationMinutes: 10,
        xpReward: 50,
        quiz: [],
      },
      {
        _id: `${courseId}_l5`,
        title: 'Multiplication Quiz',
        order: 5,
        type: 'quiz',
        content: '',
        durationMinutes: 10,
        xpReward: 60,
        quiz: [
          { question: 'What is 3 × 5?', options: ['12', '13', '15', '18'], correctIndex: 2, explanation: '3 × 5 = 15. Think of 3 groups of 5 items.' },
          { question: 'What is 6 × 4?', options: ['20', '22', '24', '26'], correctIndex: 2, explanation: '6 × 4 = 24.' },
          { question: 'A farmer plants 7 rows with 8 seeds each. How many seeds?', options: ['54', '56', '58', '60'], correctIndex: 1, explanation: '7 × 8 = 56 seeds.' },
        ],
      },
      {
        _id: `${courseId}_l6`,
        title: 'Division',
        order: 6,
        type: 'text',
        content: '# Division\n\nDivision means splitting into equal groups.\n\n**12 ÷ 4 = 3** means splitting 12 into 4 equal groups gives 3 in each group.\n\nIf you share 12 mangoes equally among 4 friends, each person gets 3.',
        durationMinutes: 10,
        xpReward: 50,
        quiz: [],
      },
      {
        _id: `${courseId}_l7`,
        title: 'Fractions',
        order: 7,
        type: 'quiz',
        content: '# Fractions\n\nA fraction represents a part of a whole.\n\n**½** means one out of two equal parts.\n\nIf you cut a yam into 4 equal pieces and take 1 piece, you have **¼** of the yam.',
        durationMinutes: 12,
        xpReward: 60,
        quiz: [
          { question: 'A circle is cut into 2 equal parts. Each part is:', options: ['¼', '½', '⅓', '⅔'], correctIndex: 1, explanation: 'Two equal parts of a whole = one half (½) each.' },
          { question: 'Which fraction is larger? ½ or ¼?', options: ['¼', '½', 'They are equal', 'Cannot say'], correctIndex: 1, explanation: '½ = 0.5 and ¼ = 0.25, so ½ is larger.' },
        ],
      },
      {
        _id: `${courseId}_l8`,
        title: 'Maths Champion 🏆',
        order: 8,
        type: 'quiz',
        content: '# Final Challenge\n\nYou have come so far! This final quiz covers everything you have learned.',
        durationMinutes: 15,
        xpReward: 80,
        quiz: [
          { question: '25 + 17 = ?', options: ['40', '41', '42', '43'], correctIndex: 2, explanation: '25 + 17 = 42.' },
          { question: '50 - 23 = ?', options: ['25', '26', '27', '28'], correctIndex: 2, explanation: '50 - 23 = 27.' },
          { question: '8 × 7 = ?', options: ['54', '56', '58', '60'], correctIndex: 1, explanation: '8 × 7 = 56.' },
          { question: '36 ÷ 6 = ?', options: ['5', '6', '7', '8'], correctIndex: 1, explanation: '36 ÷ 6 = 6.' },
        ],
      },
    ],
  },
});